// AUTO-GENERATED by @chaeco/auto-router build-worker-manifest
// Do not edit manually.
// Regenerate: npx auto-router-build-manifest example/controllers ./example/worker-routes.ts --prefix /api

import type { WorkerManifestRoute } from '@chaeco/auto-router/worker-manifest'
import handler_delete_id from './controllers/delete-[id]'
import handler_get_id from './controllers/get-[id]'
import handler_put_id from './controllers/put-[id]'
import handler_get_userId_postId from './controllers/get-[userId]-[postId]'
import handler_get_userId_posts from './controllers/get-[userId]-posts'
import handler_admin_get_dashboard from './controllers/admin/get-dashboard'
import handler_admin_get_users from './controllers/admin/get-users'
import handler_auth_post_refresh from './controllers/auth/post-refresh'
import handler_post_login from './controllers/post-login'
import handler_get_users from './controllers/get-users'
import handler_users_userId_posts_get from './controllers/users/[userId]/posts/get'
import handler_users_userId_posts_post from './controllers/users/[userId]/posts/post'
import handler_users_userId_posts_get_id from './controllers/users/[userId]/posts/get-[id]'
import handler_users_userId_settings_get from './controllers/users/[userId]/settings/get'

export const routes: WorkerManifestRoute[] = [
  { pattern: '/api/:id', method: 'DELETE', handler: handler_delete_id },
  { pattern: '/api/:id', method: 'GET', handler: handler_get_id },
  { pattern: '/api/:id', method: 'PUT', handler: handler_put_id },
  { pattern: '/api/:userId/:postId', method: 'GET', handler: handler_get_userId_postId },
  { pattern: '/api/:userId/posts', method: 'GET', handler: handler_get_userId_posts },
  { pattern: '/api/admin/dashboard', method: 'GET', handler: handler_admin_get_dashboard },
  { pattern: '/api/admin/users', method: 'GET', handler: handler_admin_get_users },
  { pattern: '/api/auth/refresh', method: 'POST', handler: handler_auth_post_refresh },
  { pattern: '/api/login', method: 'POST', handler: handler_post_login },
  { pattern: '/api/users', method: 'GET', handler: handler_get_users },
  { pattern: '/api/users/:userId/posts', method: 'GET', handler: handler_users_userId_posts_get },
  { pattern: '/api/users/:userId/posts', method: 'POST', handler: handler_users_userId_posts_post },
  { pattern: '/api/users/:userId/posts/:id', method: 'GET', handler: handler_users_userId_posts_get_id },
  { pattern: '/api/users/:userId/settings', method: 'GET', handler: handler_users_userId_settings_get },
]
